### ISSUE TITLE
Fails to call dispatch#complete

### ISSUE THREAD

**Issue by tpope** [p0deje/vim-dispatch-vimshell#2]
The use of `dispatch#copen` rather than `dispatch#complete` results in a failure to close the quickfix window on success, and can lead to showing the wrong results if multiple dispatches are in play.

**Comment by p0deje** [comment]
I'm not sure what you mean by "failure to close the quickfix window on success" (it's always opened on command exit), so I've just replaced `dispatch#copen` usage with `dispatch#complete`.
